
# Front End Events Weights
EVENTS_WEIGHT={"Favorited":"1",
                    "PartnerCTAClicked":"1",
                    "ScheduleVisit":"1",
                    "proceedNoSave":"1",
                    "PriceClicked":"1",
                    "ThumbnailClicked":"1",
                    "LocaleClicked":"1",
                    "Unfavorited":"1",
                    "PhotoClicked":"1",
                    "CalculateClicked":"1",
                    "MortgageCalculatorCTAClicked":"1",
                    "ContactPartnerClicked":"1",
                    "RequestInformationClicked":"1",
                    "SimilarPropertyClicked":"1",
                    "PartnerBanner":"1",
                    "MapPinClicked":"1",
                    "CallClicked":"1",
                    "Prop-page-email":"1",
                    "ChatClicked":"1",
                    "AgentCall":"1",
                    "AgentEmail":"1",
                    "CashbackClicked":"1",
                    "StickyContactButton":"1",
                    "StickyCall":"1",
                    "StickyGetinTouch":"1",
                    "StickyChat":"1",
                    "ComponentTriggered":"1",
                    "GetURLClicked":"1",
                    }

DEFAULT_WEIGHT = 1